### ISSUE TITLE
'Config' object has no attribute 'delete_temp'

### ISSUE THREAD

**Issue by mnyon-grandkru** [StartupOS/verinfast#184]
When calling verinfast's `agent.py` on the main branch using the following config file:
```
# This is a sample config for test runs
baseurl: https://beta.startupos.dev/api/v2
report:
  uuid: 9a6e8696-f93a-4402-a64e-342ccb37592b # UUID to match to server records
modules:
  code:
    git:
      start: 2023-02-09
    dry: false
    dependencies: true
repos:
  - https://github.com/storybookjs/storybook
  - https://github.com/spring-projects/spring-framework.git
  - https://github.com/rails/rails
  - https://github.com/keeweb/keeweb

delete_temp: true
```

I've run into the following error:
```
2023-12-19 18:59:58 Skipping uploading /home/mnyon/src/dev/stuff_I_use/verinfast/results/log.txt for  to https://beta.startupos.dev/api/v2/logs.: Skipping Uploads
Traceback (most recent call last):
  File "/home/mnyon/src/dev/stuff_I_use/verinfast/src/verinfast/agent.py", line 737, in <module>
    main()
  File "/home/mnyon/src/dev/stuff_I_use/verinfast/src/verinfast/agent.py", line 719, in main
    raise e
  File "/home/mnyon/src/dev/stuff_I_use/verinfast/src/verinfast/agent.py", line 709, in main
    agent.scan()
  File "/home/mnyon/src/dev/stuff_I_use/verinfast/src/verinfast/agent.py", line 98, in scan
    self.scanRepos()
  File "/home/mnyon/src/dev/stuff_I_use/verinfast/src/verinfast/agent.py", line 542, in scanRepos
    if not self.config.dry and self.config.delete_temp:
                               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'delete_temp'
```

When printing out the config object, it looks like there's a `self.config` object as well as a `self.config.config` object. This may be the source of the confusion. Adding the following line:
`self.log(msg=str(self.config))`
shows the following output in results.txt:
```
{
    "baseUrl": "https://beta.startupos.dev/api/v2",
    "cfg_path": "/home/mnyon/.verinfast_conf.yaml",
    "config": "{'baseurl': 'https://beta.startupos.dev/api/v2', 'report': {'uuid': '9a6e8696-f93a-4402-a64e-342ccb37592b'}, 'modules': {'code': {'git': {'start': datetime.date(2023, 2, 9)}, 'dry': False, 'dependencies': True}}, 'repos': ['https://github.com/storybookjs/storybook', 'https://github.com/spring-projects/spring-framework.git', 'https://github.com/rails/rails', 'https://github.com/keeweb/keeweb'], 'delete_temp': True}",
    "corsisId": "0",
    "delete_config_after": "False",
    "dry": "False",
    "local_scan_path": "./",
    "modules": {
        "code": {
            "git": {
                "start": "2023-6-1"
            },
            "dry": false,
            "dependencies": true
        },
        "cloud": []
    },
    "output_dir": "/home/mnyon/src/dev/stuff_I_use/verinfast/results",
    "reportId": "9a6e8696-f93a-4402-a64e-342ccb37592b",
    "runDependencies": "True",
    "runGit": "True",
    "runScan": "True",
    "runSizes": "True",
    "runStats": "True",
    "server_code_separator": null,
    "server_cost_separator": null,
    "server_prefix": null,
    "shouldManualFileScan": "True",
    "shouldUpload": "False",
    "truncate_findings": "False",
    "truncate_findings_length": "30",
    "upload_conf": {
        "uuid": true,
        "prefix": "/report/",
        "code_separator": "/CorsisCode",
        "cost_separator": null
    },
    "upload_logs": "True",
    "use_uuid": "True"
}
```

Long story short; it looks like `self.config` has a `config` object in it. Is this on purpose?

**Comment by aylusltd** [comment]
possible you got a bad build @mnyon-grandkru ? `config.py` has a property `delete_temp` on the `Config` class.
https://github.com/StartupOS/verinfast/blob/main/src/verinfast/config.py#L160

I can't replicate.

**Comment by mnyon-grandkru** [comment]
@aylusltd Looking into this a bit, I think that my configuration was non-standard when I ran into this. This doesn't occur using  `0.6.0` (the latest release available by pip). We can probably close this.

Separately, is `0.6.1` available now?
