### ISSUE TITLE
Error parsing https://github.com/jianchang512/clone-voice.git

### ISSUE THREAD

**Issue by mnyon-grandkru** [StartupOS/verinfast#197]
I ran into this error when doing a run on version `0.6.1`, with the following config file:
```
# This is a sample config for test runs
baseurl: https://beta.startupos.dev/api/v2
report:
  uuid: [REDACTED] # UUID to match to server records
modules:
  code:
    git:
      start: 2023-02-09
    dependencies: true
repos:
#  - https://github.com/storybookjs/storybook
#  - https://github.com/spring-projects/spring-framework.git
#  - https://github.com/rails/rails
#  - https://github.com/keeweb/keeweb
#   - https://github.com/django/django
#   - https://github.com/cumulo-autumn/StreamDiffusion.git
#   - https://github.com/apple/ml-ferret.git
#   - https://github.com/JoeanAmier/TikTokDownloader.git
#   - https://github.com/Pythagora-io/gpt-pilot.git
#   - https://github.com/Hillobar/Rope.git
#   - https://github.com/mnotgod96/AppAgent.git
#   - https://github.com/microsoft/promptbench.git
   - https://github.com/jianchang512/clone-voice.git
```

The run returned the following output. There's a challenge resolving the version of the torch library in requirements.txt. This is also true with a local scan as well.

```
2023-12-27 01:01:17 Config: {'baseurl': 'https://beta.startupos.dev/api/v2', 'report': {'uuid': '9a6e8696-f93a-4402-a64e-342ccb37592b'}, 'modules': {'code': {'git': {'start': datetime.date(2023, 2, 9)}, 'dependencies': True}}, 'repos': ['https://github.com/jianchang512/clone-voice.git']}
2023-12-27 01:01:17 Started:
2023-12-27 01:01:17 Git status: Git is installed at /usr/bin/git.
2023-12-27 01:01:17 Processing: clone-voice.git
2023-12-27 01:01:17 Repo URL: https://github.com/jianchang512/clone-voice.git
2023-12-27 01:01:17 Temp Directory: /home/mnyon/src/dev/stuff_I_use/aws-codedeploy-github-actions-deployment/temp_repo
2023-12-27 01:01:26 Successfully cloned: https://github.com/jianchang512/clone-voice.git
2023-12-27 01:01:26 /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/agent.py@230 parseRepo: parseRepo
2023-12-27 01:01:26 Git status: Git is installed at /usr/bin/git.
2023-12-27 01:01:26 Gathering source code statistics for: clone-voice.git
2023-12-27 01:01:28 clone-voice.git Git Stats: [{'message': 'Update README.md', 'author': 'okmyworld <2867557054@qq.com>', 'commit': '751b26b993210..
2023-12-27 01:01:28 /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/agent.py@305 parseRepo: /home/mnyon/src/dev/stuff_I_use/aws-codedeploy-github-actions-deployment/results/clone-voice.git.git.log.json
2023-12-27 01:01:28 Skipping uploading /home/mnyon/src/dev/stuff_I_use/aws-codedeploy-github-actions-deployment/results/clone-voice.git.git.log.json for clone-voice.git to https://beta.startupos.dev/api/v2/git.: Skipping Uploads
2023-12-27 01:01:28 Gathering file sizes for: clone-voice.git
2023-12-27 01:01:28 Repo Size: 180091462
2023-12-27 01:01:28 Git Size: 94951987
2023-12-27 01:01:28 Skipping uploading /home/mnyon/src/dev/stuff_I_use/aws-codedeploy-github-actions-deployment/results/clone-voice.git.sizes.json for clone-voice.git to https://beta.startupos.dev/api/v2/sizes.: Skipping Uploads
2023-12-27 01:01:28 Analyzing repository with Modernmetric: clone-voice.git
2023-12-27 01:01:33 Skipping uploading /home/mnyon/src/dev/stuff_I_use/aws-codedeploy-github-actions-deployment/results/clone-voice.git.stats.json for clone-voice.git to https://beta.startupos.dev/api/v2/stats.: Skipping Uploads
2023-12-27 01:01:33 Semgrep status: Semgrep is installed at /home/linuxbrew/.linuxbrew/bin/semgrep.
2023-12-27 01:01:33 Scanning repository: clone-voice.git
2023-12-27 01:01:48 Skipping uploading /home/mnyon/src/dev/stuff_I_use/aws-codedeploy-github-actions-deployment/results/clone-voice.git.findings.json for clone-voice.git to https://beta.startupos.dev/api/v2/findings.: Skipping Uploads
2023-12-27 01:01:48 Scanning dependencies: clone-voice.git
2023-12-27 01:01:48 /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walk.py@74 walk: Dependency Scan 10%
2023-12-27 01:01:48 /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walk.py@78 walk: Dependency Scan 25%
2023-12-27 01:01:49 /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walk.py@82 walk: Dependency Scan 40%
2023-12-27 01:02:04 parseRepo Error Caught: Could not find satisfactory version for torch==2.1.2+cu121
2023-12-27 01:02:04 : Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/agent.py", line 535, in scanRepos
    self.parseRepo(temp_dir, repo_name)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/agent.py", line 492, in parseRepo
    dependencies_output_file = dependency_walk(output_file=dependencies_output_file, logger=self.log)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walk.py", line 86, in walk
    py_walker.walk(path=path)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walkers/classes.py", line 110, in walk
    self.parse(file=str(p.absolute()), expand=expand)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walkers/python.py", line 70, in parse
    temp = parseFile(filename=file, ret=ret)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walkers/python.py", line 44, in parseFile
    data += deps
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/johnnydep/lib.py", line 392, in flatten_deps
    raise JohnnyError(msg.format(dist.name, dist.specifier))
johnnydep.lib.JohnnyError: Could not find satisfactory version for torch==2.1.2+cu121

2023-12-27 01:02:04 No local repos:
2023-12-27 01:02:04 Finished repo scans:
2023-12-27 01:02:04 Finished:
2023-12-27 01:02:04 Skipping uploading /home/mnyon/src/dev/stuff_I_use/aws-codedeploy-github-actions-deployment/results/log.txt for logs to https://beta.startupos.dev/api/v2/logs.: Skipping Uploads
```

**Comment by mnyon-grandkru** [comment]
verinfast uses johnnydep to resolve repos, and as explained at this issue (https://github.com/wimglenn/johnnydep/issues/114), johnnydep only relies upon packaged releases. Closing.
