### ISSUE TITLE
Error parsing pipenv: https://github.com/pypa/pipenv.git

### ISSUE THREAD

**Issue by mnyon-grandkru** [StartupOS/verinfast#204]
A `johnnydep` run on `pipenv` returns this result:
```
➜  ~ johnnydep pipenv
2023-12-28 13:44:42 [info     ] init johnnydist                [johnnydep.lib] dist=pipenv parent=None
2023-12-28 13:44:44 [info     ] init johnnydist                [johnnydep.lib] dist=certifi parent=pipenv
2023-12-28 13:44:46 [info     ] init johnnydist                [johnnydep.lib] dist=setuptools>=67 parent=pipenv
2023-12-28 13:44:48 [info     ] init johnnydist                [johnnydep.lib] dist=virtualenv>=20.24.2 parent=pipenv
2023-12-28 13:44:51 [info     ] init johnnydist                [johnnydep.lib] dist=distlib<1,>=0.3.7 parent=virtualenv>=20.24.2
2023-12-28 13:44:52 [info     ] init johnnydist                [johnnydep.lib] dist=filelock<4,>=3.12.2 parent=virtualenv>=20.24.2
2023-12-28 13:44:54 [info     ] init johnnydist                [johnnydep.lib] dist=platformdirs<5,>=3.9.1 parent=virtualenv>=20.24.2
name                            summary
------------------------------  --------------------------------------------------------------------------------------------------
pipenv                          Python Development Workflow for Humans.
├── certifi                     Python package for providing Mozilla's CA Bundle.
├── setuptools>=67              Easily download, build, install, upgrade, and uninstall Python packages
└── virtualenv>=20.24.2         Virtual Python Environment builder
    ├── distlib<1,>=0.3.7       Distribution utilities
    ├── filelock<4,>=3.12.2     A platform independent file lock.
    └── platformdirs<5,>=3.9.1  A small Python package for determining appropriate platform-specific dirs, e.g. a "user data dir".
```

while a `verinfast` run with this file:
```
# This is a sample config for test runs
baseurl: https://beta.startupos.dev/api/v2
report:
  uuid: [REDACTED] # UUID to match to server records
modules:
  code:
    git:
      start: 2023-02-09
    dependencies: true
repos:
   - https://github.com/pypa/pipenv.git
```    

Produces this log file:
```
2023-12-28 13:37:48 Config: {'baseurl': 'https://beta.startupos.dev/api/v2', 'report': {'uuid': '9a6e8696-f93a-4402-a64e-342ccb37592b'}, 'modules': {'code': {'git': {'start': datetime.date(2023, 2, 9)}, 'dependencies': True}}, 'repos': ['https://github.com/pypa/pipenv.git']}
2023-12-28 13:37:48 Started:
2023-12-28 13:37:48 Git status: Git is installed at /usr/bin/git.
2023-12-28 13:37:48 Processing: pipenv.git
2023-12-28 13:37:48 Repo URL: https://github.com/pypa/pipenv.git
2023-12-28 13:37:48 Temp Directory: /home/mnyon/temp_repo
2023-12-28 13:38:17 Successfully cloned: https://github.com/pypa/pipenv.git
2023-12-28 13:38:17 /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/agent.py@230 parseRepo: parseRepo
2023-12-28 13:38:17 Git status: Git is installed at /usr/bin/git.
2023-12-28 13:38:18 Gathering source code statistics for: pipenv.git
2023-12-28 13:38:20 pipenv.git Git Stats: [{'message': 'news/6008.bugfix.rst - add short bugfix description', 'author': 'Nikolay Aleksandrov G..
2023-12-28 13:38:20 /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/agent.py@305 parseRepo: /home/mnyon/results/pipenv.git.git.log.json
2023-12-28 13:38:20 Skipping uploading /home/mnyon/results/pipenv.git.git.log.json for pipenv.git to https://beta.startupos.dev/api/v2/git.: Skipping Uploads
2023-12-28 13:38:20 Gathering file sizes for: pipenv.git
2023-12-28 13:38:20 Repo Size: 280797796
2023-12-28 13:38:20 Git Size: 261288906
2023-12-28 13:38:20 Skipping uploading /home/mnyon/results/pipenv.git.sizes.json for pipenv.git to https://beta.startupos.dev/api/v2/sizes.: Skipping Uploads
2023-12-28 13:38:20 Analyzing repository with Modernmetric: pipenv.git
2023-12-28 13:39:25 Skipping uploading /home/mnyon/results/pipenv.git.stats.json for pipenv.git to https://beta.startupos.dev/api/v2/stats.: Skipping Uploads
2023-12-28 13:39:25 Semgrep status: Semgrep is installed at /home/linuxbrew/.linuxbrew/bin/semgrep.
2023-12-28 13:39:25 Scanning repository: pipenv.git
2023-12-28 13:39:59 Skipping uploading /home/mnyon/results/pipenv.git.findings.json for pipenv.git to https://beta.startupos.dev/api/v2/findings.: Skipping Uploads
2023-12-28 13:39:59 Scanning dependencies: pipenv.git
2023-12-28 13:39:59 /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walk.py@74 walk: Dependency Scan 10%
2023-12-28 13:39:59 /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walk.py@78 walk: Dependency Scan 25%
2023-12-28 13:39:59 /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walk.py@82 walk: Dependency Scan 40%
2023-12-28 13:42:28 parseRepo Error Caught: Command '['/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11', '-m', 'pip', 'wheel', '-vvv', '--no-deps', '--no-cache-dir', '--disable-pip-version-check', '--progress-bar=off', 'sphinx==4.5.0,>=5']' returned non-zero exit status 1.
2023-12-28 13:42:28 : Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/agent.py", line 535, in scanRepos
    self.parseRepo(temp_dir, repo_name)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/agent.py", line 492, in parseRepo
    dependencies_output_file = dependency_walk(output_file=dependencies_output_file, logger=self.log)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walk.py", line 86, in walk
    py_walker.walk(path=path)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walkers/classes.py", line 110, in walk
    self.parse(file=str(p.absolute()), expand=expand)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walkers/python.py", line 70, in parse
    temp = parseFile(filename=file, ret=ret)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/verinfast/dependencies/walkers/python.py", line 44, in parseFile
    data += deps
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/johnnydep/lib.py", line 414, in flatten_deps
    dist = JohnnyDist(
           ^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/johnnydep/lib.py", line 83, in __init__
    self.import_names, self.metadata, self.entry_points = _get_info(
                                                          ^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/cachetools/__init__.py", line 702, in wrapper
    v = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/johnnydep/lib.py", line 519, in _get_info
    data = pipper.get(
           ^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/johnnydep/pipper.py", line 212, in get
    out = check_output(args, stderr=STDOUT, cwd=scratch_dir).decode("utf-8")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11', '-m', 'pip', 'wheel', '-vvv', '--no-deps', '--no-cache-dir', '--disable-pip-version-check', '--progress-bar=off', 'sphinx==4.5.0,>=5']' returned non-zero exit status 1.

2023-12-28 13:42:28 No local repos:
2023-12-28 13:42:28 Finished repo scans:
2023-12-28 13:42:28 Finished:
2023-12-28 13:42:28 Skipping uploading /home/mnyon/results/log.txt for logs to https://beta.startupos.dev/api/v2/logs.: Skipping Uploads
```

**Comment by SeanTConrad** [comment]
This was fixed with version 0.7.6. Upgrade to see the fix: https://pypi.org/project/verinfast/
